server:
  port: 8082

spring:
  messages:
    basename: messages
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-h2.sql

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:${ORACLE_PORT}:XE
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
  sql:
    init:
      mode: never